api/urls.py
# api/urls.py

from django.urls import path
from . import views

# Namespace for the API app
app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('comments/', views.CommentListCreateView.as_view(), name='comment-list'),
    path('comments/<int:pk>/like/', views.CommentLikeView, name='comment-like'),
    path('comments/<int:pk>/dislike/', views.CommentDislikeView, name='comment-dislike'),
]

blog/urls.py
# blog/urls.py

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from . import views

# Namespace for the API app
app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('posts/', views.PostListView, name='post-list'),
    path(
        'posts/<int:year>/<int:month>/<int:day>/<slug:slug>/',
        views.PostDetailView.as_view(),
        name='post-detail',
    ),
    path(
        'posts/<int:pk>/',
        views.PostDetailView.as_view(),
        name='post-detail'
    ),
    path('topics/', views.TopicListView.as_view(), name='topic-list'),
    path(
        'topics/<slug:slug>/',
        views.TopicDetailView.as_view(),
        name='topic-detail'
    ),
    path(
        'contact/',
        login_required(login_url='/login/')(views.ContactFormView.as_view()),
        name='contact'
    ),
    path(
        'photocontest/',
        login_required(login_url='/login/')(views.PhotoContestFormView.as_view()),
        name='photocontest'
    ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('create_post/', views.create_post, name='create_post'),
]

will/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('', include('django.contrib.auth.urls')),
    path('home/', views.HomeView.as_view(), name='home'),
    path('cal/', include('cal.urls')),
    path('blog/', include('blog.urls')),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('admin/', admin.site.urls),
    path('favicon.ico',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
    path('sign-up', views.sign_up, name='sign_up'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

class Topic(models.Model):
    """
    Represents a topic for a blog post
    """

    name = models.CharField(
        max_length = 50,
        unique = True,
    )
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        kwargs = {'slug': self.slug}
        return reverse('blog:topic-detail', kwargs=kwargs)



class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(status=self.model.PUBLISHED)

class Post(models.Model):
    """
    Represents a blog post
    """

    DRAFT = 'draft'
    PUBLISHED = 'published'
    STATUS_CHOICES = [
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published')
    ]

    title = models.CharField(
        max_length=255,
        null=False,
    )
    content = RichTextUploadingField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='blog_posts',
        null=False,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default=DRAFT,
        help_text='Set to "published" to make this post publicly visible',
        null=False,
    )
    published = models.DateTimeField(
        null=True,
        blank=True,
        help_text='The date and time this article was published',
    )
    slug = models.SlugField(
        null=False,
        help_text='The date and time this article was published',
        unique_for_date='published',
    )
    topics = models.ManyToManyField(
        Topic,
        related_name = 'blog_posts',
    )
    banner = models.ImageField(
        blank=True,
        null=True,
        help_text='A banner image for the post'
    )

    objects = PostQuerySet.as_manager()

    class Meta:
        ordering = ['-created']
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        if self.published:
            kwargs = {
                'year': self.published.year,
                'month': self.published.month,
                'day': self.published.day,
                'slug': self.slug
            }
        else:
            kwargs = {'pk': self.pk}
        
        return reverse('blog:post-detail', kwargs=kwargs)

class CommentQuerySet(models.QuerySet):
    def get_queryset(self):
        return self

class Comment(models.Model):
    APPROVED = 'approved'
    PENDING = 'pending'
    DENIED = 'post'
    APPROVED_CHOICES = [
        (APPROVED, 'Approved'),
        (PENDING, 'Pending'),
        (DENIED, 'Denied')
    ]

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=100)
    email = models.EmailField()
    text = models.TextField()
    approved = models.CharField(
        max_length=10,
        choices=APPROVED_CHOICES,
        default=APPROVED,
        help_text='Set to "Approved" to make this comment visible to users',
        null=False,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    objects = CommentQuerySet.as_manager()

    def __str__(self):
        return f'{self.name} re: {self.post}'

    class Meta:
        ordering = ['-created']

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    submitted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-submitted']

    def __str__(self):
        return f'{self.submitted.date()}: {self.email}'

class PhotoContest(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    photo = models.ImageField(
        blank=True,
        null=True,
        help_text='Image submitted by user'
    )
    submitted = models.DateTimeField(auto_now_add=True)

blog/forms.py
# blog/forms.py

from django import forms
from blog import models

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = [
            'post',
            'name',
            'email',
            'text',
        ]
        labels = {
            'text': 'Comment'
        }
        widgets = {
            'post': forms.HiddenInput(),
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = [
            "title",
            "content",
            "status",
            "topics",
            "banner",
            ]

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from . import models, forms
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, ListView
from django.contrib import messages
from datetime import datetime
import re
from django.contrib.auth.decorators import login_required, permission_required

class HomeView(TemplateView):
    """The Blog homepage"""
    template_name = 'blog/home.html'

    def get_context_data(self, **kwargs):
        # Get the parent context
        context = super().get_context_data(**kwargs)
        
        # Get last 3 posts
        latest_posts = models.Post.objects.published().order_by('-published')[:3]

        # Update the context with our context variables
        context.update({
            'latest_posts': latest_posts,
        })

        return context

class AboutView(TemplateView):
    """Renders the About page view"""
    template_name = 'blog/about.html'

def PostListView(request):
    posts = models.Post.objects.published().order_by('-published')
    if request.method == "POST":
        post_id = request.POST.get("post-id")
        post = models.Post.objects.filter(id=post_id).first()
        if post and (post.author == request.user or request.user.has_perm("main.delete_post")):
            post.delete()

    return render(request, 'blog/post_list.html', {"posts": posts})

class PostDetailView(DetailView):
    model = models.Post

    def get_queryset(self):
        # If this is a `pk` lookup, use default queryset
        if 'pk' in self.kwargs:
            return super().get_queryset()

        # Otherwise, filter on the published date
        queryset = super().get_queryset().published()
        return queryset.filter(
            published__year=self.kwargs['year'],
            published__month=self.kwargs['month'],
            published__day=self.kwargs['day'],
        )
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get the post object
        post = self.get_object()

        # Set the post field on the form
        comment_form = forms.CommentForm(initial={'post': post})
        comments = models.Comment.objects.filter(post=post)

        context['comment_form'] = comment_form
        context['comments'] = comments.order_by('-created')

        return context

class TopicListView(ListView):
    model = models.Topic
    context_object_name = 'topics'
    queryset = models.Topic.objects.filter(blog_posts__status=models.Post.PUBLISHED).distinct().order_by('name')

class TopicDetailView(DetailView):
    model = models.Topic
    def get_queryset(self):
        return super().get_queryset().order_by('blog_posts__published')

class ContactFormView(CreateView):
    model = models.Contact
    success_url = reverse_lazy('blog:home')
    fields = [
        'first_name',
        'last_name',
        'email',
        'message',
    ]

    def form_valid(self, form):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Thank you! Your message has been sent.'
        )
        return super().form_valid(form)

class PhotoContestFormView(CreateView):
    model = models.PhotoContest
    success_url = reverse_lazy('blog:home')
    fields = [
        'name',
        'email',
        'photo',
    ]

    def form_valid(self, form):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Thank you! Your submission has been received.'
        )
        return super().form_valid(form)

@login_required(login_url="/login/")
def create_post(request):
    if request.method == 'POST':
        form = forms.PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.slug = re.sub(r"[^a-zA-Z0-9 ]", "", post.title.lower()).replace(' ', '-')
            if post.status == "published":
                post.published = datetime.now()
            post.save()
            for topic in form.cleaned_data['topics']:
                post.topics.add(topic)
            post.save()
            
            return redirect("/cal/")
    else:
        form = forms.PostForm()

    return render(request, 'blog/create_post.html', {"form": form})

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block page_title %}About{% endblock %}

{% block main %}
<h1>About</h1>
<p>Who wants to know?</p>
{% endblock %}

blog/templates/blog/base.html
{% extends "base.html" %}

{% block blog %}
    <h5><strong>Blog</strong></h5>
{% endblock %}

{% block content %}
        
    <nav id="top-nav">
        <ul>
            <li><a href="{% url "blog:home" %}">Home</a></li>
            <li><a href="{% url "blog:about" %}">About</a></li>
            <li><a href="{% url "blog:post-list" %}">Posts</a></li>
            <li><a href="{% url "blog:topic-list" %}">Topics</a></li>
            <li><a href="{% url "blog:photocontest" %}">Photo Contest!</a></li>
            <li><a href="{% url "blog:contact" %}">Contact</a></li>
            <li><a href="{% url "blog:create-post" %}">Create Post</a></li>
        </ul>
    </nav>

    <main id="main-content">
        <div>
            {% block main %}
            <!-- Content for the main block will be rendered here -->
            {% endblock %}
        </div>

        <aside>
            <h2 class="text-primary">Topics:</h2>
            <ul>
                {% for topic in all_topics %}
                    <li><a href="{{ topic.get_absolute_url }}">{{ topic.name }} ({{ topic.blog_posts__count }})</a></li>
                {% endfor %}
            </ul>
        </aside>

    </main>
{% endblock content %}

blog/templates/blog/comment_form.html
{# blog/templates/blog/comment_form.html #}

<form action="{% url "api:comment-list" %}" method="post" id="comment-form">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td><button type="submit">Send</button></td>
      </tr>
    </table>
  </form>
  

blog/templates/blog/contact_form.html
{# blog/templates/blog/contact_form.html #}

{% extends "blog/base.html" %}

{% block page_title %}Contact{% endblock %}


{% block main %}

<form method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit">Submit</button>
</form>
{% endblock %}

blog/templates/blog/create_post.html
{% extends 'blog/base.html' %} {% block title %}Create a Post{% endblock %} 
{% load crispy_forms_tags %} {% block content %}
<form method="post">
  {% csrf_token %}{{form|crispy}}
  <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

blog/templates/blog/home.html
{# blog/templates/blog/home.html #}

{% extends "blog/base.html" %}

{% block main %}
<section>
  <h1>Latest posts</h1>
  {% for post in latest_posts %}
    {% include "blog/post_preview.html" %}
  {% endfor %}
</section>
{% endblock %}

blog/templates/blog/photocontest_form.html
{# blog/templates/blog/photocontest_form.html #}

{% extends "blog/base.html" %}

{% block page_title %}Submit a Photo!{% endblock %}


{% block main %}

<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit">Submit</button>
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{# blog/templates/blog/post_detail.html #}
{% extends "blog/base.html" %}
{% block page_title %}{{ post.title }}{% endblock %}

{% block main %}
<article id="post-detail-article">
  <h1>{{ post.title }}</h1>
  <div>{% if post.banner %}
    <img class='bannerimage' src="{{ post.banner.url }}" alt="Banner image">
  {% endif %}</div>
  <span class="published">Published <time>{{ post.published }}</time></span><br>
  <span class="author">{{ post.author.get_full_name }}</span>
  <span class="topic">
    {% for topic in post.topics.all %}
      <a href="{{ topic.get_absolute_url }}">{{ topic.name }}</a>&nbsp;&nbsp;
    {% endfor %}
  </span>
  <section class="content">{{ post.content|safe|linebreaks }}</section>
  
  {% load static %}
</article>


<section class="comments">
  {% if comments %}
    <h3>Latest comments</h3>
    {% for comment in comments %}
      <div class="comment">
        <span class="by-line">By {{ comment.name }} | <time>{{ comment.created }}</time></span>
        {{ comment.text|linebreaks }}
        <a id='like{{ comment.pk }}' class='like' href="/api/comments/{{ comment.pk }}/like/">
        <img class='likedislike' src="{% static "blog/thumbsup.png" %}" /> {{ comment.likes }}</a>
        &nbsp;&nbsp;&nbsp;
        <a id='dislike{{ comment.pk }}' class='dislike' href="/api/comments/{{ comment.pk }}/dislike/">
        <img class='likedislike' src="{% static "blog/thumbsdown.png" %}" /> {{ comment.dislikes }}</a>
      </div>
    {% endfor %}
  {% endif %}

  {% if user.is_authenticated %}
  <h3>Leave a comment</h3>
    {% with form=comment_form %}
      {% include "blog/comment_form.html" %}
    {% endwith %}
  {% endif %}
</section>

{% endblock %}

blog/templates/blog/post_list.html
{# blog/templates/blog/post_list.html #}

{% extends "blog/base.html" %}

{% block page_title %}Posts{% endblock %}

{% block main %}
<h1>Posts</h1>

{% for post in posts %}
  {% include "blog/post_preview.html" %}
{% endfor %}

{% endblock %}

blog/templates/blog/post_preview.html
{# blog/templates/blog/post_preview.html #}
<div class="card-body d-flex flex-row justify-content-between">
  <div>
  <article class="post-preview">
  <h2>{{ post.title }}</h2>
  <time>{{ post.published }}</time>
  <section class="teaser">
    {{ post.content|striptags|truncatewords:20|safe }}
  </section>
  <p><a href="{{ post.get_absolute_url }}">Read more &rarr; </a></p>
  </article>
  </div>
  <div>
    {% if user == post.author or perms.main.delete_post %}
      <form method="post">
        {% csrf_token %}
        <button
          type="submit"
          class="btn btn-danger"
          name="post-id"
          value="{{post.id}}"
          >
          Delete
        </button>
      </form>
    {% endif %}
  </div>
</div>

blog/templates/blog/topic_detail.html
{# blog/templates/blog/topic_detail.html #}
{% extends "blog/base.html" %}
{% block page_title %}{{ topic.name }}{% endblock %}

{% block main %}

{% for post in topic.blog_posts.all %}
    {% if post.status == 'published' %}
        {% include "blog/post_preview.html" %}
    {% endif %}
{% endfor %}

{% endblock %}

blog/templates/blog/topic_list.html
{# blog/templates/blog/topic_list.html #}

{% extends "blog/base.html" %}

{% block page_title %}Topics{% endblock %}

{% block main %}
<h1>Topics</h1>
<ul>
{% for topic in topics %}
  <li><a href="{{ topic.get_absolute_url }}">{{ topic.name }} &rarr; </a></li>
{% endfor %}
</ul>
{% endblock %}