api/urls.py
# api/urls.py

from django.urls import path
from . import views

# Namespace for the API app
app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('comments/', views.CommentListCreateView.as_view(), name='comment-list'),
    path('comments/<int:pk>/like/', views.CommentLikeView, name='comment-like'),
    path('comments/<int:pk>/dislike/', views.CommentDislikeView, name='comment-dislike'),
]

blog/urls.py
# blog/urls.py

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from . import views

# Namespace for the API app
app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('posts/', views.PostListView, name='post-list'),
    path(
        'posts/<int:year>/<int:month>/<int:day>/<slug:slug>/',
        views.PostDetailView.as_view(),
        name='post-detail',
    ),
    path(
        'posts/<int:pk>/',
        views.PostDetailView.as_view(),
        name='post-detail'
    ),
    path('topics/', views.TopicListView.as_view(), name='topic-list'),
    path(
        'topics/<slug:slug>/',
        views.TopicDetailView.as_view(),
        name='topic-detail'
    ),
    path(
        'contact/',
        login_required(login_url='/login/')(views.ContactFormView.as_view()),
        name='contact'
    ),
    path(
        'photocontest/',
        login_required(login_url='/login/')(views.PhotoContestFormView.as_view()),
        name='photocontest'
    ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('create_post/', views.create_post, name='create_post'),
]

cal/urls.py
from os import path
# cal/urls.py
from . import views
from django.urls import path

app_name = 'cal'

urlpatterns = [
    path('', views.CalView, name='home'),
    path('<int:year>/<int:month>', views.CalView, name='home'),
    path('addevent/', views.addCalEvent, name='add-cal-event'),
]

will/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('', include('django.contrib.auth.urls')),
    path('home/', views.HomeView.as_view(), name='home'),
    path('cal/', include('cal.urls')),
    path('blog/', include('blog.urls')),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('admin/', admin.site.urls),
    path('favicon.ico',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
    path('sign-up', views.sign_up, name='sign_up'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Will's Place{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <link rel="stylesheet" href="{% static 'cal/cal.css' %}" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <div>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">{% block home %}Home{% endblock %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:home' %}">{% block blog %}Blog{% endblock %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cal:home' %}">{% block calendar %}Calendar{% endblock %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'privacy' %}">{% block privacy %}Privacy{% endblock %}</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <span class="navbar-text">Logged in as {{user.username}} | </span>
                            <li class="nav-item">
                                <a class="nav-link" href="/logout">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="/login">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        {% if messages %}
            <div class="django-messages">
            {% for message in messages %}
                <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
            </div>
        {% endif %}
        <main role="main" class="pb-3">
            {% block content %}
            <!-- Content for the main block will be rendered here -->
            {% endblock %}
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 Will Habsburg - <a href="{% url 'privacy' %}">Privacy</a>
        </div>
    </footer>

    {% block js %}
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/site.js' %}" asp-append-version="true"></script>
        <script src="{% static 'blog/csrf.js' %}"></script>
        <script src="{% static 'blog/comments.js' %}"></script>
        <script src="{% static 'blog/likedislike.js' %}"></script>
    {% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}


{% block home %}
    <h5><strong>Home</strong></h5>
{% endblock home %}
    


{% block content %}
    <h1>Home</h1>
{% endblock content %}
    

templates/privacy.html
{% extends "base.html" %}
{% load static %}

{% block privacy %}
    <h5><strong>Privacy</strong></h5>
{% endblock %}

{% block content %}
    <h1>Privacy</h1>
    <img src="{% static 'images/cat.png' %}" alt="Rainbow Cat Wearing Headphones">
    <p>This cat controls the data.  What (s)he does with it, nobody knows.</p>
{% endblock content %}
    